### ISSUE TITLE
Title of chapter 7 is same with chapter 6 in Chinese translate version

### ISSUE THREAD

**Issue by zujia** [xiaoweiChen/Learn-LLVM-12#2]
The title of chapter 7 in the English version is "Advanced IR Generation", but the title in the Chinese version is “生成高级语言结构的 IR”, it may be confused with the title of Chapter 6.

**Comment by xiaoweiChen** [comment]
Thanks for your feedback. This issue is fixed.
You can download the latest PDF(Learn-LLVM-12-20211229.pdf) from Release Page.
